# Generated by Django 3.0.8 on 2020-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_userfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
