# Generated by Django 3.0.8 on 2020-08-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200803_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_posted',
            field=models.DateField(),
        ),
    ]
