# Generated by Django 3.0.8 on 2020-08-05 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200804_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
