# Generated by Django 3.0.8 on 2020-09-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200804_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like_count',
        ),
    ]
