# Generated by Django 3.0.8 on 2020-09-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200917_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
